version: "3.8"
services:
  wiki:
    image: hhk7734/wiki-loliot-net:1.0
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
      - /etc/nginx/conf.d:/etc/nginx/conf.d

  # certbot:
  #   image: certbot/certbot:latest
  #   command: certonly --webroot --webroot-path=/var/www/certbot --email hhk7734@gmail.com --agree-tos --no-eff-email -d loliot.net -d wiki.loliot.net
  #   volumes:
  #     - /etc/letsencrypt:/etc/letsencrypt
  #     - /var/www/certbot:/var/www/certbot
  #     - /var/log/letsencrypt:/var/log/letsencrypt
  #   deploy:
  #     replicas: 1
  #     resources:
  #       reservations:
  #         memory: "256Mi"